Creating the Pandas DataFrame

In [3]:
import pandas as pd

data = {
    "EmployeeID": [201,202,203,204,205,206,207,208,209,210],
    "Name": ["Sarah", "Michael", "Jennifer", "David", "Lisa", "James", "Emma", "Robert", "Sophia", "William"],
    "Department": ["Engineering", "Sales", "Marketing", "Engineering", "HR", "Sales", "Engineering", "Marketing", "Sales", "HR"],
    "Salary": [85000,62000,71000,92000,58000,68000,78000,75000,65000,60000],
    "Performance Score": [4,3,5,5,4,4,3,4,5,3],
    "Years of Service": [5,3,7,8,4,6,2,5,4,3]
}

df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         10 non-null     int64
 1   Name               10 non-null     object
 2   Department         10 non-null     object
 3   Salary             10 non-null     int64
 4   Performance Score  10 non-null     int64
 5   Years of Service   10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

In [4]:
df.head()

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
1,202,Michael,Sales,62000,3,3
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
4,205,Lisa,HR,58000,4,4

In [5]:
df.tail()

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
5,206,James,Sales,68000,4,6
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5
8,209,Sophia,Sales,65000,5,4
9,210,William,HR,60000,3,3

In [6]:
df.describe()

       EmployeeID        Salary  Performance Score  Years of Service
count    10.00000     10.000000          10.000000         10.000000
mean    205.50000  71400.000000           4.000000          4.700000
std       3.02765  11137.524161           0.816497          1.888562
min     201.00000  58000.000000           3.000000          2.000000
25%     203.25000  62750.000000           3.250000          3.250000
50%     205.50000  69500.000000           4.000000          4.500000
75%     207.75000  77250.000000           4.750000          5.750000
max     210.00000  92000.000000           5.000000          8.000000

Displaying only 'Name', 'Department', and 'Salary' columns

In [7]:
df[["Name", "Department", "Salary"]]

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

displaying the employee at row position 5 using .iloc()

In [10]:
df.iloc[4]

EmployeeID             205
Name                  Lisa
Department              HR
Salary               58000
Performance Score        4
Years of Service         4
Name: 4, dtype: object

displaying the employee with EmployeeID 208 using .loc()

In [12]:
df.loc[df["EmployeeID"]==208]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
7         208  Robert  Marketing   75000                  4                 5

In [14]:
df.loc[7]

EmployeeID                 208
Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 7, dtype: object

Filter and displaying all employees from the 'Engineering' department

In [15]:
df[df["Department"] == "Engineering"]

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

Filter and displaying all employees with Salary greater than 70000

In [16]:
df[df["Salary"] > 70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

Filter and displaying employees from 'Sales' department with Performance Score >= 4

In [17]:
df[(df["Department"] == "Sales") & (df["Performance Score"] >= 4)]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

Sorting the entire DataFrame by Salary in descending order and displaying the top 3 highest-paid employees

In [19]:
result = df.sort_values("Salary", ascending=False)
result.head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

Sorting by Department (ascending) and then by Salary (descending) within each department

In [20]:
df.sort_values(["Department","Salary"], ascending=[True,False])

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3